### ISSUE TITLE
Problem with Wifi connection when running  jit_enabler_better.py

### ISSUE THREAD

**Issue by Pietjepuk8** [fritzlb/iOS17-JIT-WIN#10]
When I run the jit_enabler_better.py script I get a problem where my wifi get's disabled. The script installs the network driver, and that is when it happens.

I tried reconnecting the ipad, tried another usb port, rebooted my laptop. I also tried manually uninstalling the WeTest drivers. I also delete the driver software or else every time I connect my iPad to my computer Wifi get's disabled. 

```
C:\Users\local\ONEDRI~1\Desktop\IOS17-~1>python jit_enabler_better.py net.kdt.pojavlauncher.RB7T77W696
Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.RB7T77W696
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fdb9:7d13:f421::1 49979
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Error mounting DiskImage : Traceback (most recent call last):
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002ACE58B5670>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/doronz88/DeveloperDiskImage/git/trees/main?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002ACE58B5670>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\mounter.py", line 120, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 362, in auto_mount
    auto_mount_personalized(lockdown)
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 348, in auto_mount_personalized
    repo = DeveloperDiskImageRepository.create()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\developer_disk_image\repo.py", line 30, in create
    return cls(cls._query(DEVELOPER_DISK_IMAGE_REPO_TREE_URL)['tree'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\developer_disk_image\repo.py", line 61, in _query
    response = json.loads(requests.get(url).text)
                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\local\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/doronz88/DeveloperDiskImage/git/trees/main?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002ACE58B5670>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)"))
```

**Comment by fritzlb** [comment]
It seems like this issue occurs when downloading the developer disk image… with the actual connection to your device, everything seems to be fine.
If I interpret the log correctly, the PC manages to connect to your iPad, then for whatever reason your WiFi connection crashes and therefore the script can’t mount the developer disk image which would be required to continue. 
The thing I don’t get is why your WiFi crashes and in your log, I don’t see anything related to that. It is entirely possible that this is a weird driver bug, but I didn’t write that driver (or anything from pymobiledevice3 tbh)

Do you have the non MS store version of iTunes installed on your PC? Apparently it also brings drivers or sth that are required by pymobiledevice3. Also a weird question, your PC isn’t connected to your iPad hotspot, right?
Also, what kind of hardware do you use for WiFi?

**Comment by fritzlb** [comment]
https://www.windowscentral.com/how-change-priority-order-network-adapters-windows-10
apparently it is possible to configure a priority for the network adapters, could you try to prioritize your WiFi adapter over the WeTestUSB?

**Comment by Pietjepuk8** [comment]
Hi,

I have installed the web version of iTunes and iCloud. I am also not using the iPad hotspot. As for the hardware I am using, it's a Intel AC 8265. The weird thing is that it goes into this mode:
![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/5551309/f4f3a7c3-7120-46cf-8c81-431608a09cd3)

Then I can enable Wifi, and I can see my networks but only for a few seconds, then Wifi turns off again.

**Comment by fritzlb** [comment]
Is there any software on your PC that might disable WiFi if Ethernet is connected? Also, did prioritizing help?

**Comment by fritzlb** [comment]
https://woshub.com/disable-wi-fi-when-ethernet-cable-connected/ this guide for example shows that there are PCs that automatically do this. Try finding out more about your setup, according to a quick google search the intel wireless tool has an option to adjust that.
As I don't have the same setup as you I'm afraid I can't help any further, so I'll close this for now. If there's anything else with my script that doesn't work, feel free to open another issue :)

**Comment by Pietjepuk8** [comment]
Thanks for getting on this track! I found it, it was an anoying HP LAN/WLAN/WWAN switcher service that caused it. Disabled it and I was able to succesfully run the script.
