### ISSUE TITLE
OSError: [WinError 10051] while starting app

### ISSUE THREAD

**Issue by sni0088** [fritzlb/iOS17-JIT-WIN#12]
>python jit_enabler_better.py com.utmapp.UTM
Getting bundle ID...
Got bundle ID: com.utmapp.UTM
starting tunnel to device...
Sucessfully created tunnel: fdf0:c30d:c1e4::1 58659
Starting app...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 53, in handle_parse_result
    return super().handle_parse_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 249, in rsd
    rsd.connect()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

**Comment by fritzlb** [comment]
You aren't using the correct bundle ID. Your sideloding software does modify com.utmapp.UTM because every bundle ID can only be registered once with Apple and only the apple ID (or better: Xcode team) that registered it will be able to use it. 
If you're using sideloadly you can set a custom bundle ID under advanced options, for altstore there's the button "view app IDs"

**Comment by sni0088** [comment]
C:\Users\Amin\Desktop\IOS17-~1>python jit_enabler_better.py com.utmapp.UTM.58396532U8
Getting bundle ID...
Got bundle ID: com.utmapp.UTM.58396532U8
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd46:d0a2:a813::1 58675
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 53, in handle_parse_result
    return super().handle_parse_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 249, in rsd
    rsd.connect()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "C:\Program Files\Python312\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

**Comment by fritzlb** [comment]
The script opens a network tunnel over USB to your iOS device and tries to communicate with it, which somehow fails. I fear it could be many things like a wrongly configured windows firewall, weird network settings, third party software etc

**Comment by fritzlb** [comment]
According to another user's issue this might be fixable by reinstalling the WeTest USB driver. If you delete that in device manager it should reinstall when plugging in your device again or at least once you start the script. 
Also, what troubleshooting steps did you already try?

**Comment by fritzlb** [comment]
The iPad not Charging is normal, did you try rebooting using the restart button yet? (Yes on windows it does make a difference if you shutdown and boot or restart)

**Comment by sni0088** [comment]
Yes, I restarted Windows, but it still gives the same error

**Comment by fritzlb** [comment]
I honestly don't know why this is happening on your system. If you can, I'd try another PC. 
If you can't do that maybe check your windows firewall settings as well as your network adapters, there should show up two extra adapters if your device is plugged in. 
Idk if there's any software installed on your system that's restricting network access, something like that could cause this too.
I'm not sure if it could help to use a different windows user, sometimes there's something misconfigured in the user profile

**Comment by ConstantineVac** [comment]
```
H:\IPAs\iOS17-JIT-WIN-main\iOS17-JIT-WIN-main>python jit_enabler_better.py {com.rileytestut.Delta.6F4CF8W84U}
Getting bundle ID...
Got bundle ID: {com.rileytestut.Delta.6F4CF8W84U}
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd55:7bd1:513e::1 50550
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "c:\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\python310\lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "c:\python310\lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "c:\python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\python310\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "c:\python310\lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
  File "c:\python310\lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
    result = self._channel.receive_plist()
  File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
    return self._service.recv_plist(self)[0]
  File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
    data = archiver.unarchive(data)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
  File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
    raise DvtException(archive_obj.decode('NSUserInfo'))
pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "{com.rileytestut.Delta.6F4CF8W84U}"'}
```

I have this issue which looks similar to the original post. I have noticed that momentarily after the error displays, I get reconnected to the internet. (I am connected through ethernet)

**Comment by ConstantineVac** [comment]
> ```
> H:\IPAs\iOS17-JIT-WIN-main\iOS17-JIT-WIN-main>python jit_enabler_better.py {com.rileytestut.Delta.6F4CF8W84U}
> Getting bundle ID...
> Got bundle ID: {com.rileytestut.Delta.6F4CF8W84U}
> starting tunnel to device...
> This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
> Sucessfully created tunnel: fd55:7bd1:513e::1 50550
> Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
> Diskimage already mounted.
> Starting app...
> Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
>   File "c:\python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "c:\python310\lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
>     main()
>   File "c:\python310\lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
>     cli()
>   File "c:\python310\lib\site-packages\click\core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\python310\lib\site-packages\click\core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python310\lib\site-packages\click\core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python310\lib\site-packages\click\core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\python310\lib\site-packages\click\core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "c:\python310\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
>     callback(service_provider=service_provider, **kwargs)
>   File "c:\python310\lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
>     pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
>     result = self._channel.receive_plist()
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
>     return self._service.recv_plist(self)[0]
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
>     data = archiver.unarchive(data)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
>     return Unarchive(plist).top_object()
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 267, in top_object
>     return self.decode_object(self.top_uid)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
>     obj = klass.decode_archive(ArchivedObject(raw_obj, self))
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
>     user_info = archive_obj.decode('NSUserInfo')
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
>     return self._unarchiver.decode_key(self.object, key)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
>     return self.decode_object(val)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
>     obj = klass.decode_archive(ArchivedObject(raw_obj, self))
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
>     val = archive_obj.decode_index(val_uids[i])
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
>     return self._unarchiver.decode_object(index)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
>     obj = klass.decode_archive(ArchivedObject(raw_obj, self))
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
>     user_info = archive_obj.decode('NSUserInfo')
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
>     return self._unarchiver.decode_key(self.object, key)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
>     return self.decode_object(val)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
>     obj = klass.decode_archive(ArchivedObject(raw_obj, self))
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
>     val = archive_obj.decode_index(val_uids[i])
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
>     return self._unarchiver.decode_object(index)
>   File "c:\python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
>     obj = klass.decode_archive(ArchivedObject(raw_obj, self))
>   File "c:\python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
>     raise DvtException(archive_obj.decode('NSUserInfo'))
> pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "{com.rileytestut.Delta.6F4CF8W84U}"'}
> ```
> 
> I have this issue which looks similar to the original post. I have noticed that momentarily after the error displays, I get reconnected to the internet. (I am connected through ethernet)

Please ignore my post, I was not paying attention and I didn't remove the { } from the bundle id. I did that and the process was completed correctly !

**Comment by fritzlb** [comment]
Thanks for the follow up :)
