### ISSUE TITLE
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):

### ISSUE THREAD

**Issue by ilyHapple** [fritzlb/iOS17-JIT-WIN#26]
D:\iOS17-JIT-WIN-main>python jit_enabler_better.py net.kdt.pojavluncher.RW96Y35W5R
Getting bundle ID...
Got bundle ID: net.kdt.pojavluncher.RW96Y35W5R
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd51:9e2e:2f99::1 57363
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
    result = self._channel.receive_plist()
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
    return self._service.recv_plist(self)[0]
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
    data = archiver.unarchive(data)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
  File "C:\Users\Elppahs\AppData\Local\Programs\Python\Python310\lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
    raise DvtException(archive_obj.decode('NSUserInfo'))
pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "net.kdt.pojavluncher.RW96Y35W5R"'}

I've even rebooted.

Windows 11 23H2

python-3.10.8 

iPhone 13 Pro Max

ios 17.3.1

![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/31878663/77249421-0d7b-4c69-94f5-86190a56039f)

**Comment by fritzlb** [comment]
You wrote pojavluncher instead of pojavlauncher as bundle ID
