### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by DatUub** [fritzlb/iOS17-JIT-WIN#4]
C:\Users\jgenova\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py com.netflix.NGP.BloonsTDSix
Getting bundle ID...
Got bundle ID: com.netflix.NGP.BloonsTDSix
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd93:87c7:5e4f::1 50039
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
    result = self._channel.receive_plist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
    return self._service.recv_plist(self)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
    data = archiver.unarchive(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jgenova\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
    raise DvtException(archive_obj.decode('NSUserInfo'))
pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "com.netflix.NGP.BloonsTDSix"'}

**Comment by fritzlb** [comment]
According to the log there’s no app with that bundle ID installed on your device. Please check it again :)
If you used sideloadly you can manually specify the bundle ID (or see it in the install log on the bottom), the process for altstore is shown in my video

**Comment by DatUub** [comment]
I how do I see the bundle id from the install log

**Comment by fritzlb** [comment]
You might need to press the button in the bottom corner, then a log window should open at the bottom. In theory there should be something like “bundle ID” somewhere. If you don’t find that, you can specify your own bundle ID (pretty much anything as long as no app with that bundle ID exists on Apples App Store) in advanced options

**Comment by DatUub** [comment]
I resigned it using a custom bundle ID. Worked perfectly :)

**Comment by fritzlb** [comment]
Thanks for the feedback, I appreciate it :)
