### ISSUE TITLE
FileNotFound WinError 2

### ISSUE THREAD

**Issue by Kiro598** [fritzlb/iOS17-JIT-WIN#44]
Ran into a problem, here's the log.

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mynamehere\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mynamehere\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

What should I do to fix the issue?

**Comment by Kiro598** [comment]
Forgot to add this, but I've tried re-installing Python as well

**Comment by fritzlb** [comment]
Vous pouvez essayer d‘exécuter install_slow.bat, ça le repare souvent :)

**Comment by Kiro598** [comment]
Merci pour la réponse rapide! Néanmoins même en exécutant install.slow.bat il semble que le problème persiste

**Comment by fritzlb** [comment]
Pas de problème :)
Je crois que redémarrer l'ordinateur ne change rien, ouais ? 
Dans ce cas pouvez vous partager toutes les messages debug ? Merci bcp

**Comment by Kiro598** [comment]
Voici le message

Run debugging commands...
This might take a few minutes.
Traceback (most recent call last):
  File "C:\Users\name\Desktop\IOS17-~1\jit_enabler_better.py", line 135, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by fritzlb** [comment]
Ahhh je vois
Python ne peut pas trouver lldb, c‘est une application pour le debugging. Install.bat/install_slow.bat la télécharge normalement, il semble que ce n’est pas marché. L’archive zip, elle est est décompressé ? Aussi, vous avez une bonne connexion Internet ?

**Comment by Kiro598** [comment]
Oui je crois que l'archive zip est décompressé. Par contre, ma connexion internet actuelle n'est pas bonne. Vous pensez que c'est ce qui cause le problème?

**Comment by fritzlb** [comment]
Oui, c'est une possibilité. Vous pouvez essayer de télécharger lldb manuellement ici (~0.5Go): https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-msvcrt-x86_64.zip
Il faut le décompresser, après ça placez le dossier avec 'bin' dans le même dossier que le fichier python :)

**Comment by Cpump16** [comment]
I am getting the same error code but I am trying to add this to dolphin emulator, I’m not sure how to fix the problem. If you could explain in depth what I should do to fix it, I would really appreciate it.

**Comment by fritzlb** [comment]
Try install slow.bat first. If that doesn't work, did at least the restart dialog appear?

**Comment by Cpump16** [comment]
I have been trying to fix the problem for two hours and all I had to do was use the beta of dolphin instead lol 😂. Sorry for wasting your time and thanks for responding so quick.
