### ISSUE TITLE
Unable to run command with Play! bundle id.

### ISSUE THREAD

**Issue by naimfauzi** [fritzlb/iOS17-JIT-WIN#46]
Not sure if Play! is just problematic but I've gotten this out when running the bundle id command:

```
C:\Users\Naim\Desktop\work\IOS17-~1>python jit_enabler_better.py com.virtualapplications.play.3XVBS6VGG4 True
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: com.virtualapplications.play.3XVBS6VGG4
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Error opening a tunnel. : [b'Traceback (most recent call last):\r\n', b'  File "C:\\Python39\\lib\\runpy.py", line 197, in _run_module_as_main\r\n', b'    return _run_code(code, main_globals, None,\r\n', b'  File "C:\\Python39\\lib\\runpy.py", line 87, in _run_code\r\n', b'    exec(code, run_globals)\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\__main__.py", line 156, in <module>\r\n', b'    main()\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\__main__.py", line 98, in main\r\n', b'    cli()\r\n', b'  File "C:\\Python39\\lib\\site-packages\\click\\core.py", line 1157, in __call__\r\n', b'    return self.main(*args, **kwargs)\r\n', b'  File "C:\\Python39\\lib\\site-packages\\click\\core.py", line 1078, in main\r\n', b'    rv = self.invoke(ctx)\r\n', b'  File "C:\\Python39\\lib\\site-packages\\click\\core.py", line 1682, in invoke\r\n', b'    cmd_name, cmd, args = self.resolve_command(ctx, args)\r\n', b'  File "C:\\Python39\\lib\\site-packages\\click\\core.py", line 1729, in resolve_command\r\n', b'    cmd = self.get_command(ctx, cmd_name)\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\__main__.py", line 82, in get_command\r\n', b"    mod = __import__(f'pymobiledevice3.cli.{CLI_GROUPS[name]}', None, None, ['cli'])\r\n", b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\cli\\remote.py", line 10, in <module>\r\n', b'    from pymobiledevice3.cli.cli_common import BaseCommand, RSDCommand, print_json, prompt_device_list, sudo_required, \\\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\cli\\cli_common.py", line 19, in <module>\r\n', b'    from pymobiledevice3.lockdown import LockdownClient, create_using_usbmux\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\lockdown.py", line 18, in <module>\r\n', b'    from pymobiledevice3.ca import ca_do_everything\r\n', b'  File "C:\\Python39\\lib\\site-packages\\pymobiledevice3\\ca.py", line 3, in <module>\r\n', b'    from cryptography import x509\r\n', b'  File "C:\\Python39\\lib\\site-packages\\cryptography\\x509\\__init__.py", line 7, in <module>\r\n', b'    from cryptography.x509 import certificate_transparency, verification\r\n', b'  File "C:\\Python39\\lib\\site-packages\\cryptography\\x509\\certificate_transparency.py", line 11, in <module>\r\n', b'    from cryptography.hazmat.bindings._rust import x509 as rust_x509\r\n', b'ImportError: DLL load failed while importing _rust: The specified procedure could not be found.\r\n']
```

**Comment by fritzlb** [comment]
The bundle ID looks fine and idk if your app supports JIT. Anyway, this shouldn't happen. 
Could you try manually running python -m pymobiledevice3 remote start-tunnel and share the output here?
Also, are you using a recent version of python? According to a quick Google search this issue might happen with older versions of python

**Comment by naimfauzi** [comment]
My bad I didn't realize I had an older python version installed. I have updated my python and I'm receiving pymobiledevice3 not found. Ran install.bat again and rebooted but still got the same error (pymobiledevice3 not found). I'm currently running install_slow.bat to see if there is any difference.

**Comment by fritzlb** [comment]
Can you try to manually install pymobiledevice3? Install slow will do nothing regarding this I think
pip install pymobiledevice3

**Comment by naimfauzi** [comment]
I was having problems with my PATHS and I couldn't run pip. But I managed to fix my Paths now Im getting this error.

```
C:\Users\Naim\Desktop\work\IOS17-~1>python jit_enabler_better.py com.virtualapplications.play.3XVBS6VGG4
Getting bundle ID...
Got bundle ID: com.virtualapplications.play.3XVBS6VGG4
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-04-23 03:05:04\x1b[0m \x1b[35mDESKTOP-RKQNCQQ\x1b[0m \x1b[34m__main__[17172]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']
```

**Comment by naimfauzi** [comment]
My device is connected properly as I could access AltServer through AltStore but it's showing me this error.

**Comment by fritzlb** [comment]
Re-run install.bat
Theres a recent version of pymobiledevice3 that doesn't handle the driver installation as expected, hence there's no information regarding the version of the driver.
install.bat will install an older one :)

**Comment by naimfauzi** [comment]
Ah! I just simply reconnected my device now I its running! Thank you so much man been dying to run PS2 games on my iPad. So now I'm assuming I can disconnect my device and would have to re-run the command or the shortcut file to renable Jit?

**Comment by fritzlb** [comment]
Yeah, exactly. Great it works for you :)
I‘ll close this then, if there’s anything unclear feel free to open a new issue :)
