### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Zyxify4545** [fritzlb/iOS17-JIT-WIN#64]
when ever i try to run the  the sciipt python jit_enabler_better.py  it gives me this

Getting bundle ID...
Got bundle ID: me.oatmealdome.dolphinios-njb.3KMUNN52BG
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd9d:46da:d3e5::1 59517
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 1880
Starting debug server...
Started debug server with connection details: [fd9d:46da:d3e5::1]:52835
Run debugging commands...
This might take a few minutes.
Traceback (most recent call last):
  File "C:\Users\getsi\Desktop\HELLO\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 141, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\getsi\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\getsi\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified  please help

**Comment by fritzlb** [comment]
Did you try running install_slow.bat? For whatever reason on some windows systems lldb doesn’t get downloaded/extracted properly
