### ISSUE TITLE
"error opening a tunnel"

### ISSUE THREAD

**Issue by RJmakes** [fritzlb/iOS17-JIT-WIN#65]
everything is installed and downloaded. when i try and run the script, i get this every time.

C:\Users\user\DOWNLO~1\IOS17-~1\IOS17-~1>jit_enabler_better.py net.kdt.pojavlauncher.2HYZC7G47W
Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.2HYZC7G47W
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Error opening a tunnel. : [b'Traceback (most recent call last):\r\n', b'  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 194, in _run_module_as_main\r\n', b'    return _run_code(code, main_globals, None,\r\n', b'  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 87, in _run_code\r\n', b'    exec(code, run_globals)\r\n', b'  File "C:\\Users\\user\\DOWNLO~1\\IOS17-~1\\IOS17-~1\\pymobiledevice3\\__main__.py", line 5, in <module>\r\n', b'    import click\r\n', b"ModuleNotFoundError: No module named 'click'\r\n"]

any help?

**Comment by fritzlb** [comment]
You could try running `pip install click`, idk why it didn’t install automatically. Somehow pymobiledevice3 with its dependencies keeps breaking over and over again

**Comment by RJmakes** [comment]
pip installed, still same error

**Comment by fritzlb** [comment]
That’s really weird. If you start python (just type python into a terminal window) and try to run `import click`, does that work?
