### ISSUE TITLE
my jit is stuck

### ISSUE THREAD

**Issue by Gabriel7376363** [fritzlb/iOS17-JIT-WIN#67]
so i was trying to enable jit for pojav lancher and for like 10 minutes there is this message "This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC" so i try to kill all python process but nothing i rebooted the pc like 5 times but nothing,please help

**Comment by Rylazius** [comment]
can you run the script with True (like `python jit.py bundle_id_here True`) and send the log here?

**Comment by Gabriel7376363** [comment]
so i testest with but still stuck there is the log i don?t if this is the log so you tell me:
C:\Users\pappa\OneDrive\Desktop\IOS17-~1>set "params="

C:\Users\pappa\OneDrive\Desktop\IOS17-~1>cd /d "C:\Users\pappa\OneDrive\Desktop\IOS17-~1\"   && (if exist "C:\Users\pappa\AppData\Local\Temp\getadmin.vbs" del "C:\Users\pappa\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\Users\pappa\OneDrive\Desktop\IOS17-~1\"" && ""C:\Users\pappa\OneDrive\Desktop\IOS17-~1\OPENTE~1.BAT"" ", "", "runas", 1   1>>"C:\Users\pappa\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\pappa\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\Users\pappa\OneDrive\Desktop\IOS17-~1>python jit_enabler_better.py net.kdt.pojavlauncher.QS35Z853DR true
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: net.kdt.pojavlauncher.QS35Z853DR
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.

**Comment by fritzlb** [comment]
How did you reboot your PC? If you didn't click "restart" but instead shutdown and started it again, those two things aren't the same. 
Also any chance you could try running the following command in an admin terminal and post the output here? `python -m pymobiledevice3 remote start-tunnel`

**Comment by Gabriel7376363** [comment]
> How did you reboot your PC? If you didn't click "restart" but instead shutdown and started it again, those two things aren't the same. Also any chance you could try running the following command in an admin terminal and post the output here? `python -m pymobiledevice3 remote start-tunnel`

yes i rebooted my pc and is the same i tried the command with amministrator permission and it tell me this:
C:\Users\pappa\OneDrive\Desktop\IOS17-~1>python -m pymobiledevice3 remote start-tunnel
2024-05-07 17:22:04 gaming wintun[10932] INFO WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.
2024-05-07 17:22:05 gaming wintun[10932] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-05-07 17:22:05 gaming wintun[10932] INFO use existing WeTestUsbFilter driver.
2024-05-07 17:22:05 gaming wintun[10932] INFO use existing WeTestUsbNcm driver.
Traceback (most recent call last):
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\client.py", line 95, in connect
    protocol.connect(addr)
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 504, in connect
    self._connect(now=now)
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 1217, in _connect
    self._initialize(self._peer_cid.cid)
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 1373, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 146, in wrapper
    func(*args, **kwargs)
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\client.py", line 100, in connect
    protocol.close()
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 52, in close
    self.transmit()
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 102, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pappa\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 541, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>

**Comment by Gabriel7376363** [comment]
> Any chance you didn’t use my install script or updated python libraries? Anyway, try running `pip install qh3==0.15.1` After that this error shouldn’t occur anymore

thank you so much it worked updating the python libraries,have a great day

**Comment by fritzlb** [comment]
Thanks for the update ☺️
