### ISSUE TITLE
Hello I'm new to github and I need help with this Altstore JIT problem "FileNotFoundError: [WinError 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by Flashback000** [fritzlb/iOS17-JIT-WIN#68]
Hey so im trying to install JIT on my iPhone 14 and ive gotten past all of the steps for opening Dolphini OS beta. And I get it to open the app and it just ends it with:

C:\Users\W1\Dropbox\PC\DOWNLO1\IOS17-1\IOS17-1>python jit_enabler_better.py me.oatmealdome.DolphiniOS-njb-patreon-beta.6YL8X7BVJJ
Getting bundle ID...
Got bundle ID: me.oatmealdome.DolphiniOS-njb-patreon-beta.6YL8X7BVJJ
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fdf2:a2c4:a5d7::1 59066
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 1242
Starting debug server...
Started debug server with connection details: [fdf2:a2c4:a5d7::1]:50214
Run debugging commands...
This might take a few minutes.
Traceback (most recent call last):
File "C:\Users\W1\Dropbox\PC\DOWNLO1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 141, in
lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Wl\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\W\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

The "FileNotFoundError: [WinError 2] The system cannot find the file specified" is what im having issues with

I had issues with the "It seems like you device isnt connected" but i just fixed it and now it keeps telling me that. Not really sure what to do. I could possibly just be dumb because i know nothing about this and im just following tutorials.
Im not sure what this is or how to fix it please help. I am new to github so sorry if i didnt explain enough

**Comment by fritzlb** [comment]
That happens sometimes. The install script downloads lldb, a file that's needed. You can either try to run install_slow.bat, that fixes it usually. If it doesn't, open the script in a text editor, copy the link, download the file manually using your preferred web browser and extract it. Make sure the llvm folder that contains a bin folder hasn't been renamed and is in the same directory as the script.
