### ISSUE TITLE
DeveloperDiskImage already mounted

### ISSUE THREAD

**Issue by 10kwon** [fritzlb/iOS17-JIT-WIN#72]
```

C:\Users\(Korean Username)\DOWNLO~1\IOS17-~1>python jit_enabler_better.py me.oatmealdome.DolphiniOS-njb-patreon-beta errors='replace'
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: me.oatmealdome.DolphiniOS-njb-patreon-beta
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd87:a60c:ad41::1 54395
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
2024-05-11 22:26:15 DESKTOP-Q2T6RUE pymobiledevice3.cli.mounter[7100] ERROR DeveloperDiskImage already mounted

Diskimage already mounted.
Starting app...
(b'', b'Traceback (most recent call last):\r\n  File "<frozen runpy>", line 198, in _run_module_as_main\r\n  File "<frozen runpy>", line 88, in _run_code\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\__main__.py", line 156, in <module>\r\n    main()\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\__main__.py", line 98, in main\r\n    cli()\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1157, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1078, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1434, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 783, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\cli\\cli_common.py", line 172, in wrap_callback_calling\r\n    callback(service_provider=service_provider, **kwargs)\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\cli\\developer.py", line 198, in launch\r\n    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\dvt\\instruments\\process_control.py", line 74, in launch\r\n    result = self._channel.receive_plist()\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 261, in receive_plist\r\n    return self._service.recv_plist(self)[0]\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 438, in recv_plist\r\n    data = archiver.unarchive(data)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 23, in unarchive\r\n    return Unarchive(plist).top_object()\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 267, in top_object\r\n    return self.decode_object(self.top_uid)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 129, in decode_archive\r\n    raise DvtException(archive_obj.decode(\'NSUserInfo\'))\r\npymobiledevice3.exceptions.DvtException: {\'BSErrorCodeDescription\': \'NotFound\', \'NSLocalizedFailureReason\': \'Application info provider (FBSApplicationLibrary) returned nil for "me.oatmealdome.DolphiniOS-njb-patreon-beta"\'}\r\n')
Unknown error. : (b'', b'Traceback (most recent call last):\r\n  File "<frozen runpy>", line 198, in _run_module_as_main\r\n  File "<frozen runpy>", line 88, in _run_code\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\__main__.py", line 156, in <module>\r\n    main()\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\__main__.py", line 98, in main\r\n    cli()\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1157, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1078, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 1434, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\click\\core.py", line 783, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\cli\\cli_common.py", line 172, in wrap_callback_calling\r\n    callback(service_provider=service_provider, **kwargs)\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\cli\\developer.py", line 198, in launch\r\n    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\dvt\\instruments\\process_control.py", line 74, in launch\r\n    result = self._channel.receive_plist()\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 261, in receive_plist\r\n    return self._service.recv_plist(self)[0]\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 438, in recv_plist\r\n    data = archiver.unarchive(data)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 23, in unarchive\r\n    return Unarchive(plist).top_object()\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 267, in top_object\r\n    return self.decode_object(self.top_uid)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\\xc0\xcc\xb1\xd4\xba\xf3\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 129, in decode_archive\r\n    raise DvtException(archive_obj.decode(\'NSUserInfo\'))\r\npymobiledevice3.exceptions.DvtException: {\'BSErrorCodeDescription\': \'NotFound\', \'NSLocalizedFailureReason\': \'Application info provider (FBSApplicationLibrary) returned nil for "me.oatmealdome.DolphiniOS-njb-patreon-beta"\'}\r\n')

```

**Comment by fritzlb** [comment]
Your bundle ID isn't correct. Please use the personalized, correct one. 

You're only seeing this error with the disk image cause you are starting the script using debug mode by passing any argument after the bundle ID
