### ISSUE TITLE
an attempt was made to access a socket in a way that was forbidden

### ISSUE THREAD

**Issue by zrm9901** [fritzlb/iOS17-JIT-WIN#76]
I started up a shortcut file with the updated version of pymobiledevice3 and with the lockdown tunnel instead of remote and it finally established the tunnel and got past the "device not connected error" but then went on the give the error in the title. Here is the full log. 

C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1>set "params="

C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1>cd /d "C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1\"   && (if exist "C:\Users\zrm99\AppData\Local\Temp\getadmin.vbs" del "C:\Users\zrm99\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1\"" && ""C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1\shortcut.bat"" ", "", "runas", 1   1>>"C:\Users\zrm99\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\zrm99\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py com.antique.Folium-Sudachi.L87J43T458
Getting bundle ID...
Got bundle ID: com.antique.Folium-Sudachi.L87J43T458
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd49:a3c8:f086::1 63164
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\__main__.py", line 170, in <module>
    main()
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\__main__.py", line 100, in main
    cli()
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\cli\cli_common.py", line 58, in handle_parse_result
    return super().handle_parse_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\cli\cli_common.py", line 223, in rsd
    get_asyncio_loop().run_until_complete(rsd.connect())
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 56, in connect
    await self.service.connect()
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\remote\remotexpc.py", line 54, in connect
    self.service_connection = ServiceConnection.create_using_tcp(self.address[0], self.address[1],
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\service_connection.py", line 81, in create_using_tcp
    sock = socket.create_connection((hostname, port))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Users\zrm99\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

C:\Users\zrm99\DOWNLO~1\IOS17-~1\IOS17-~1>

**Comment by zrm9901** [comment]
nvm apparently a vpn breaks it
