### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Vpsutdocquyen** [fritzlb/iOS17-JIT-WIN#80]
help me

C:\Users\yeuho\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py net.kdt.pojavlauncher.JKNH7T527D
Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.JKNH7T527D
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fdac:65f8:a382::1 63852
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 1471
Starting debug server...
Started debug server with connection details: [fdac:65f8:a382::1]:61550
Run debugging commands...
This might take a few minutes.
Traceback (most recent call last):
  File "C:\Users\yeuho\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 141, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeuho\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\yeuho\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by fritzlb** [comment]
You probably didn't unzip the archive or didn't run install.bat. 
Also I'm not sure anymore if this still works at all. 
I probably won't be able to help too much as I'm quite busy, but it's cool to see people still trying to use this :)
Also I'd recommend SideJIT server which is wayyy more professional

**Comment by edntdftdftg** [comment]
works for me, and SideJIT Is a pain bro. SideJIT Is full of errors when you try to connect another device. this be simple: plug the cable and enter bundle id. thats it.
