### ISSUE TITLE
Could not find file: WinError 2

### ISSUE THREAD

**Issue by Adalbar3333** [fritzlb/iOS17-JIT-WIN#83]
```py
Traceback (most recent call last):
  File "C:\Users\jjaya\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 141, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jjaya\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jjaya\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified```

**Comment by fritzlb** [comment]
Something went wrong downloading the dependencies. Try install_slow.bat, if that doesn’t fix it try to manually download lldb
