### ISSUE TITLE
error launching the app

### ISSUE THREAD

**Issue by bySantana-8** [fritzlb/iOS17-JIT-WIN#9]
I get the following error when running the script:
Getting bundle ID...
Got bundle ID: bundle_id
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd34:5b7e:67ef::1 55187
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
    result = self._channel.receive_plist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
    return self._service.recv_plist(self)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
    data = archiver.unarchive(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
    raise DvtException(archive_obj.decode('NSUserInfo'))
pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "bundle_id"'}

I have checked that the AppID is correct several times and refreshing the apps, but it still gives me the same error.

**Comment by fritzlb** [comment]
The script thinks "bundle_id" is your bundle ID. Replace that with the actual bundle ID as the only parameter you start my script with :)
